# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 23:45
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BelongTO',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('quantity', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('name', models.CharField(max_length=255,
                                          primary_key=True,
                                          serialize=False,
                                          unique=True)),
                ('price', models.IntegerField()),
                ('description', models.URLField(
                    default='No description yet', max_length=500)),
                ('type', models.CharField(choices=[
                    ('Laptop', 'Laptop'),
                    ('Personal Computer', 'Personal computer'),
                    ('Monoblock', 'Monoblock')], default='Personal Computer',
                    max_length=30)),
                ('pic', models.ImageField(
                    blank=True, max_length=1000, upload_to='static')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('date', models.DateTimeField(default=datetime.date.today)),
                ('code', models.CharField(
                    max_length=6, primary_key=True,
                    serialize=False, unique=True)),
                ('total', models.DecimalField(
                    decimal_places=2, default=0.0, max_digits=10)),
                ('is_open', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    primary_key=True,
                    serialize=False,
                    to=settings.AUTH_USER_MODEL)),
                ('telephone', models.CharField(default='+', max_length=20)),
                ('birth_date', models.DateField()),
                ('address', models.CharField(max_length=200)),
                ('gender', models.CharField(blank=True, choices=[
                    ('M', 'Male'), ('F', 'Female')],
                                            default='M',
                                            max_length=1)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='my_site.UserProfile'),
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(
                through='my_site.BelongTO', to='my_site.Computer'),
        ),
        migrations.AddField(
            model_name='belongto',
            name='item',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='my_site.Computer'),
        ),
        migrations.AddField(
            model_name='belongto',
            name='order',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='my_site.Order'),
        ),
    ]
