# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-10 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0002_auto_20161210_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='type',
            field=models.CharField(
                choices=[
                    ('Monoblock', 'Monoblock'),
                    ('Personal Computer', 'Personal computer'),
                    ('Laptop', 'Laptop')],
                default='Personal Computer', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.AutoField(
                max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
