# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0003_auto_20161210_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='pic',
            field=models.ImageField(
                blank=True, max_length=1000,
                upload_to='images'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='type',
            field=models.CharField(
                choices=[
                    ('Personal Computer', 'Personal computer'),
                    ('Laptop', 'Laptop'),
                    ('Monoblock', 'Monoblock')],
                default='Personal Computer', max_length=30),
        ),
    ]
