# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0004_auto_20161211_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='description',
            field=models.TextField(
                default='No description yet', max_length=500),
        ),
        migrations.AlterField(
            model_name='computer',
            name='type',
            field=models.CharField(choices=[
                ('Laptop', 'Laptop'),
                ('Monoblock', 'Monoblock'),
                ('Personal Computer', 'Personal computer')],
                default='Personal Computer',
                max_length=30),
        ),
    ]
