# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0006_auto_20161211_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='pic',
            field=models.ImageField(
                blank=True, max_length=1000,
                upload_to='/static/'),
        ),
    ]
