# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0007_auto_20161213_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='belongto',
            name='id',
            field=models.AutoField(primary_key=True,
                                   serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='type',
            field=models.CharField(choices=[
                ('Laptop', 'Laptop'),
                ('Monoblock', 'Monoblock'),
                ('Personal Computer', 'Personal computer')],
                default='Personal Computer', max_length=30),
        ),
    ]
