# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0008_auto_20161213_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='belongto',
            name='id',
            field=models.CharField(max_length=255,
                                   primary_key=True,
                                   serialize=False,
                                   unique=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='type',
            field=models.CharField(choices=[
                ('Personal Computer', 'Personal computer'),
                ('Laptop', 'Laptop'), ('Monoblock', 'Monoblock')],
                default='Personal Computer', max_length=30),
        ),
    ]
