# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0010_auto_20161213_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='pic',
            field=models.ImageField(blank=True, max_length=1000, upload_to='/Users/hp/PycharmProjects/hw/media'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='type',
            field=models.CharField(choices=[('Personal Computer', 'Personal computer'), ('Laptop', 'Laptop'), ('Monoblock', 'Monoblock')], default='Personal Computer', max_length=30),
        ),
    ]
